

spring:
  datasource:
    url: >
      jdbc:mysql://${db_host:localhost}:${db_port:8889}/${db_database:apiadmin}
      ?useSSL=false
      &useUnicode=true
      &characterEncoding=utf8
      &serverTimezone=GMT%2b8
      &allowMultiQueries=true
    username: ${db_username:root}
    password: ${db_password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 1
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 from dual

mybatis-plus:
  mapper-locations:  classpath*:mapper/**/*Mapper.xml
  logEnable: true
  global-config:
    column-underline: true
    db-config:
      id-type: auto
      table-underline: true