server.port: ${PORT:3333}
spring.config.import:
  - optional:file:${user.home}/.xx/env.properties
  - optional:classpath:env-local.properties # 越靠后优先级越高，后面覆盖前面
#debug: true
logging:
  level:
    root: info
    org.springframework.kafka: warn
    org.apache.kafka: warn
    okhttp3: error


dy.config:
  web:
    log-enable: true
    log-level: info    # 用于控制打印log的日志等级，默认info，支持debug和warn
    log-mode: interceptor
    log-ignore-keywords: health,metrics  # 用于屏蔽某些关键词，逗号分隔
    response-time-format: yyyy-MM-dd HH:mm:ss # 可选值： 默认 timestamps，ISO-8601，或SimpleDateFormat能接受的pattern
    response-long-to-string: false  # 如果有long类型返回时被截断，需要以string形式返回，但这个配置是全局的
    rest-controller-error-advice-enable: true # 开启DyWebExceptionHandler拦截Rest请求异常
    websocket-enable: false # 是否开启websocket，会与web共享一个端口

#spring.boot.admin.client.url: http://springboot-admin-server.geesatcom.corp
#spring.boot.admin.client.instance.prefer-ip: true
management.endpoints.web.exposure.include: '*'


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  log-enable: true # 是否输出日志
  log-level: info # 设置sql日志以什么等级输出，而不是选择输出哪个等级的日志
  log-ignore-keywords:   # 过滤掉不想输出的关键字，如表名
  global-config:
    column-underline: true
    db-config:
      id-type: auto
      table-underline: true

spring:
  application.name: demo
  profiles.active: ${PROFILE:local}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    #账号配置
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE:demos}?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=True&allowMultiQueries=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1 from dual

